# Generated by Django 5.1.4 on 2026-05-30 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('bank', 'Bank / MFI'), ('insurer', 'Insurer'), ('supplier', 'Supplier'), ('offtaker', 'Off-taker'), ('other', 'Other')], default='other', max_length=24)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('rate_limit_per_min', models.PositiveIntegerField(default=60)),
                ('webhook_secret', models.CharField(blank=True, help_text='HMAC secret for signed webhooks.', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsentGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scopes', models.JSONField(default=list, help_text='Subset of registry|aggregate|activity_events.')),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_consents', to='farms.farm')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='partners.partner')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('partner', 'farm'), name='uniq_consent_partner_farm')],
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefix', models.CharField(db_index=True, help_text='First chars of the key, for lookup + display.', max_length=12)),
                ('key_hash', models.CharField(help_text='SHA-256 of the full key. Raw key never stored.', max_length=64)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='partners.partner')),
            ],
            options={
                'indexes': [models.Index(fields=['prefix', 'is_active'], name='partners_ap_prefix_0a43cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartnerAuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
                ('scope', models.CharField(blank=True, max_length=24)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='farms.farm')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='partners.partner')),
            ],
            options={
                'indexes': [models.Index(fields=['partner', '-at'], name='partners_pa_partner_4d1556_idx')],
            },
        ),
    ]
