# Generated by Django 5.1.4 on 2026-05-30 17:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('category', models.CharField(blank=True, help_text='vet, drone, soil_testing, …', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('price_kobo', models.BigIntegerField(default=0)),
                ('revenue_share_pct', models.PositiveSmallIntegerField(default=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('suspended', 'Suspended')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='partners.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleInstall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('price_kobo', models.BigIntegerField(default=0)),
                ('gitako_cut_kobo', models.BigIntegerField(default=0)),
                ('developer_take_kobo', models.BigIntegerField(default=0)),
                ('payment_reference', models.CharField(blank=True, max_length=128)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('uninstalled_at', models.DateTimeField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_installs', to='farms.farm')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installs', to='devstore.developermodule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('module', 'farm'), name='uniq_module_install')],
            },
        ),
    ]
