# Generated by Django 5.1.4 on 2026-05-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], default='sms', max_length=8),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='recipient',
            field=models.CharField(db_index=True, default='', help_text='Phone (E.164) for SMS, email address for email.', max_length=255),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['recipient', 'channel', 'purpose', '-created_at'], name='accounts_ot_recipie_83ea4c_idx'),
        ),
    ]
