# Generated by Django 5.1.4 on 2026-05-22 14:57

import apps.tenancy.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.UUIDField(default=apps.tenancy.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('target_table', models.CharField(max_length=64)),
                ('target_id', models.UUIDField()),
                ('action', models.CharField(max_length=16)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['target_table', 'target_id', '-at'], name='tenancy_aud_target__172433_idx')],
            },
        ),
    ]
