# Generated by Django 5.1.4 on 2026-05-24 13:37

import apps.tenancy.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0003_activity_performed_by_alter_activity_actor_user'),
        ('enterprises', '0001_initial'),
        ('farms', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=apps.tenancy.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client_seq', models.BigIntegerField(default=0)),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('momo', 'Mobile money'), ('supplier_credit', 'Supplier credit'), ('customer_credit', 'Customer credit')], default='cash', max_length=24)),
                ('name', models.CharField(max_length=120)),
                ('opening_balance_kobo', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='farms.farm')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=apps.tenancy.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client_seq', models.BigIntegerField(default=0)),
                ('kind', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], max_length=12)),
                ('amount_kobo', models.BigIntegerField(help_text='Signed: expense and source side of transfer are negative.')),
                ('receipt_key', models.CharField(blank=True, help_text='S3 key for the receipt photo, if any.', max_length=255)),
                ('posted_at', models.DateTimeField(db_index=True)),
                ('transfer_pair_id', models.UUIDField(blank=True, help_text='Two paired transactions share this id for a transfer.', null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.account')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='activities.activity')),
                ('enterprise', models.ForeignKey(blank=True, help_text="If set, the transaction rolls into this enterprise's P&L.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='enterprises.enterprise')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='farms.farm')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='farms.party')),
                ('ref_inventory_movement', models.ForeignKey(blank=True, help_text='Set when this expense was auto-generated by an inventory receipt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.inventorymovement')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='finance.transaction')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('farm', 'name'), name='uniq_account_per_farm'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['farm', '-posted_at'], name='finance_tra_farm_id_d1b9e4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', '-posted_at'], name='finance_tra_account_9212cb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['enterprise', '-posted_at'], name='finance_tra_enterpr_c03454_idx'),
        ),
    ]
