# Generated by Django 5.1.4 on 2026-05-30 16:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('produce', 'Produce'), ('livestock', 'Livestock'), ('input', 'Farm input'), ('other', 'Other')], default='produce', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('unit', models.CharField(blank=True, help_text='bags, kg, birds, crates…', max_length=24)),
                ('price_kobo', models.BigIntegerField(default=0, help_text='Asking price in kobo (per unit or lot).')),
                ('price_is_per_unit', models.BooleanField(default=True)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('photo_keys', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('withdrawn', 'Withdrawn')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='farms.farm')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='marketplace_status_0bc035_idx'), models.Index(fields=['kind', 'status'], name='marketplace_kind_36d959_idx')],
            },
        ),
    ]
