# Generated by Django 5.1.4 on 2026-05-30 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InputFinancing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Inputs requested (e.g. 10 bags NPK).', max_length=255)),
                ('value_kobo', models.BigIntegerField()),
                ('repay_after_days', models.PositiveIntegerField(default=120)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('fulfilled', 'Fulfilled'), ('repaid', 'Repaid'), ('declined', 'Declined')], default='requested', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_financing', to='farms.farm')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_financing', to='partners.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('weather_index', 'Weather-index'), ('livestock_mortality', 'Livestock mortality')], max_length=24)),
                ('coverage_kobo', models.BigIntegerField(help_text='Sum insured in kobo.')),
                ('premium_kobo', models.BigIntegerField(default=0, help_text='Quoted premium in kobo.')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('quoted', 'Quoted'), ('bound', 'Bound'), ('declined', 'Declined')], default='requested', max_length=12)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_quotes', to='farms.farm')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_quotes', to='partners.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_kobo', models.BigIntegerField()),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('term_days', models.PositiveIntegerField(default=180)),
                ('credit_score_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('disbursed', 'Disbursed'), ('repaid', 'Repaid'), ('defaulted', 'Defaulted'), ('declined', 'Declined')], default='draft', max_length=12)),
                ('offer_terms', models.JSONField(blank=True, default=dict)),
                ('disbursement_reference', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='farms.farm')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_applications', to='partners.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
