"""Finance primitives — Account · Transaction.

Per PRD M5:
- An **Account** is where money sits: cash on hand, a bank account, a mobile-
  money wallet, or a credit ledger (supplier/customer credit). Farm-scoped.
- A **Transaction** moves money. Three kinds: income · expense · transfer.
  Amounts are signed for raw math: expense and the source side of a transfer
  are negative; income and the destination side positive.

Transactions link to a Party (counterparty), an Enterprise (for P&L
attribution), an Activity (for cost tracing), and/or an InventoryMovement
(when M4 receipts auto-generate the expense).

Per PRD non-functional requirements: financial rows are immutable once posted.
Corrections happen via reversal entries (`reversal_of` FK).
"""
from __future__ import annotations

from django.db import models

from apps.activities.models import Activity
from apps.enterprises.models import Enterprise
from apps.farms.models import Farm, Party
from apps.inventory.models import InventoryMovement
from apps.tenancy.models import TenantScopedModel


class Account(TenantScopedModel):
    TYPE_CASH = "cash"
    TYPE_BANK = "bank"
    TYPE_MOMO = "momo"
    TYPE_SUPPLIER_CREDIT = "supplier_credit"
    TYPE_CUSTOMER_CREDIT = "customer_credit"
    TYPE_CHOICES = [
        (TYPE_CASH, "Cash"),
        (TYPE_BANK, "Bank"),
        (TYPE_MOMO, "Mobile money"),
        (TYPE_SUPPLIER_CREDIT, "Supplier credit"),
        (TYPE_CUSTOMER_CREDIT, "Customer credit"),
    ]

    farm = models.ForeignKey(Farm, on_delete=models.CASCADE, related_name="accounts")
    type = models.CharField(max_length=24, choices=TYPE_CHOICES, default=TYPE_CASH)
    name = models.CharField(max_length=120)
    opening_balance_kobo = models.BigIntegerField(default=0)
    currency = models.CharField(max_length=3, default="NGN")

    class Meta:
        ordering = ["name"]
        constraints = [
            models.UniqueConstraint(fields=["farm", "name"], name="uniq_account_per_farm"),
        ]

    def __str__(self) -> str:
        return f"{self.name} ({self.get_type_display()})"


class Transaction(TenantScopedModel):
    KIND_INCOME = "income"
    KIND_EXPENSE = "expense"
    KIND_TRANSFER = "transfer"
    KIND_CHOICES = [
        (KIND_INCOME, "Income"),
        (KIND_EXPENSE, "Expense"),
        (KIND_TRANSFER, "Transfer"),
    ]

    farm = models.ForeignKey(Farm, on_delete=models.CASCADE, related_name="transactions")
    account = models.ForeignKey(Account, on_delete=models.PROTECT, related_name="transactions")
    kind = models.CharField(max_length=12, choices=KIND_CHOICES)
    amount_kobo = models.BigIntegerField(
        help_text="Signed: expense and source side of transfer are negative.",
    )
    party = models.ForeignKey(
        Party, null=True, blank=True, on_delete=models.SET_NULL,
        related_name="transactions",
    )
    enterprise = models.ForeignKey(
        Enterprise, null=True, blank=True, on_delete=models.SET_NULL,
        related_name="transactions",
        help_text="If set, the transaction rolls into this enterprise's P&L.",
    )
    activity = models.ForeignKey(
        Activity, null=True, blank=True, on_delete=models.SET_NULL,
        related_name="transactions",
    )
    ref_inventory_movement = models.ForeignKey(
        InventoryMovement, null=True, blank=True, on_delete=models.SET_NULL,
        related_name="transactions",
        help_text="Set when this expense was auto-generated by an inventory receipt.",
    )
    receipt_key = models.CharField(
        max_length=255, blank=True,
        help_text="S3 key for the receipt photo, if any.",
    )
    posted_at = models.DateTimeField(db_index=True)
    reversal_of = models.ForeignKey(
        "self", null=True, blank=True, on_delete=models.SET_NULL,
        related_name="reversed_by",
    )
    transfer_pair_id = models.UUIDField(
        null=True, blank=True,
        help_text="Two paired transactions share this id for a transfer.",
    )
    description = models.CharField(max_length=255, blank=True)

    class Meta:
        ordering = ["-posted_at"]
        indexes = [
            models.Index(fields=["farm", "-posted_at"]),
            models.Index(fields=["account", "-posted_at"]),
            models.Index(fields=["enterprise", "-posted_at"]),
        ]

    def __str__(self) -> str:
        sign = "+" if self.amount_kobo > 0 else "−"
        return f"{sign}₦{abs(self.amount_kobo) / 100:,.0f} {self.kind} on {self.account.name}"
