# Generated by Django 5.1.4 on 2026-05-24 07:17

import apps.tenancy.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0003_activity_performed_by_alter_activity_actor_user'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=apps.tenancy.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client_seq', models.BigIntegerField(default=0)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('seed', 'Seed'), ('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide / agrochemical'), ('feed', 'Feed'), ('vet', 'Vet supplies / drugs'), ('produce', 'Harvested produce'), ('livestock', 'Live animals / birds'), ('processed', 'Processed goods'), ('supplies', 'Tools & supplies'), ('other', 'Other')], default='other', max_length=16)),
                ('unit', models.CharField(default='unit', help_text='bags, kg, L, doses, birds, units…', max_length=24)),
                ('valuation_method', models.CharField(choices=[('weighted_avg', 'Weighted average'), ('fifo', 'FIFO')], default='weighted_avg', max_length=16)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0, help_text="Trigger 'low stock' when on-hand drops below this.", max_digits=14)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='farms.farm')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=apps.tenancy.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client_seq', models.BigIntegerField(default=0)),
                ('name', models.CharField(max_length=120)),
                ('location_note', models.CharField(blank=True, max_length=255)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='farms.farm')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=apps.tenancy.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client_seq', models.BigIntegerField(default=0)),
                ('op', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment')], max_length=12)),
                ('qty', models.DecimalField(decimal_places=3, help_text='Signed for raw math: issues are negative, receipts positive.', max_digits=14)),
                ('unit_cost_kobo', models.BigIntegerField(default=0, help_text='Per-unit cost in kobo at the time of this movement.')),
                ('transfer_pair_id', models.UUIDField(blank=True, help_text='Two paired movements share this id for a transfer.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem')),
                ('ref_activity', models.ForeignKey(blank=True, help_text='Set when this movement was caused by an activity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='activities.activity')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.store')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('farm', 'name'), name='uniq_item_per_farm'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('farm', 'name'), name='uniq_store_per_farm'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['item', 'store', '-occurred_at'], name='inventory_i_item_id_3cabb1_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['tenant_id', '-occurred_at'], name='inventory_i_tenant__c0d103_idx'),
        ),
    ]
