# Generated by Django 5.1.4 on 2026-05-22 14:57

import apps.tenancy.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncNote',
            fields=[
                ('id', models.UUIDField(default=apps.tenancy.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client_seq', models.BigIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'sync_note',
            },
        ),
        migrations.CreateModel(
            name='SyncTag',
            fields=[
                ('id', models.UUIDField(default=apps.tenancy.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client_seq', models.BigIntegerField(default=0)),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(default='green', max_length=16)),
            ],
            options={
                'db_table': 'sync_tag',
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.UUIDField(default=apps.tenancy.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('server_seq', models.BigIntegerField(db_index=True)),
                ('table', models.CharField(max_length=64)),
                ('row_id', models.UUIDField()),
                ('op', models.CharField(choices=[('insert', 'Insert'), ('update', 'Update'), ('delete', 'Delete')], max_length=8)),
                ('payload', models.JSONField(default=dict)),
                ('device_id', models.CharField(blank=True, max_length=64)),
                ('client_seq', models.BigIntegerField(default=0)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['server_seq'],
                'indexes': [models.Index(fields=['tenant_id', 'server_seq'], name='sync_change_tenant__34ec10_idx'), models.Index(fields=['table', 'row_id'], name='sync_change_table_3601da_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'server_seq'), name='uniq_changelog_tenant_seq')],
            },
        ),
        migrations.CreateModel(
            name='SyncCursor',
            fields=[
                ('id', models.UUIDField(default=apps.tenancy.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('device_id', models.CharField(max_length=64)),
                ('last_server_seq_acked', models.BigIntegerField(default=0)),
                ('last_pull_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_cursors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'tenant_id', 'device_id'), name='uniq_cursor_user_tenant_device')],
            },
        ),
    ]
