# Generated by Django 5.1.4 on 2026-05-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='weather',
            field=models.CharField(blank=True, choices=[('just_rained', 'Just rained'), ('about_to_rain', 'About to rain'), ('clear', 'Clear · no rain expected')], help_text='Conditions when the activity happened.', max_length=16),
        ),
    ]
