# Generated by Django 5.1.4 on 2026-05-22 16:17

import apps.tenancy.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.UUIDField(default=apps.tenancy.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client_seq', models.BigIntegerField(default=0)),
                ('type', models.CharField(choices=[('crop_cycle', 'Crop cycle'), ('flock', 'Poultry flock')], max_length=24)),
                ('name', models.CharField(max_length=120)),
                ('lifecycle_state', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='planned', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('attrs', models.JSONField(default=dict)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprises', to='farms.farm')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
    ]
