# Generated by Django 5.1.4 on 2026-05-24 20:44

import apps.tenancy.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterprisePlan',
            fields=[
                ('id', models.UUIDField(default=apps.tenancy.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client_seq', models.BigIntegerField(default=0)),
                ('budget_lines', models.JSONField(default=list)),
                ('expected_yield_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Total expected yield in kg (crops) or total kg of birds (flocks).', max_digits=12, null=True)),
                ('expected_unit_price_kobo', models.BigIntegerField(blank=True, help_text='Expected price per kg in kobo.', null=True)),
                ('price_reference', models.CharField(blank=True, help_text="Free text — e.g. 'Iseyin market avg.' or 'Sayedero contract'.", max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='enterprises.enterprise')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
