# Generated by Django 5.1.4 on 2026-05-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0002_enterpriseplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='type',
            field=models.CharField(choices=[('crop_cycle', 'Crop cycle'), ('flock', 'Poultry flock'), ('herd', 'Livestock herd')], max_length=24),
        ),
    ]
