# Generated by Django 5.1.4 on 2026-05-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0003_alter_enterprise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='type',
            field=models.CharField(choices=[('crop_cycle', 'Crop cycle'), ('flock', 'Poultry flock'), ('herd', 'Livestock herd'), ('pond', 'Fish pond'), ('processing_line', 'Processing line')], max_length=24),
        ),
    ]
