# Generated by Django 5.1.4 on 2026-05-30 21:53

import apps.tenancy.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_performed_by_alter_activity_actor_user'),
        ('enterprises', '0004_alter_enterprise_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonTask',
            fields=[
                ('id', models.UUIDField(default=apps.tenancy.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client_seq', models.BigIntegerField(default=0)),
                ('activity_type', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('target_date', models.DateField(db_index=True)),
                ('source', models.CharField(blank=True, max_length=32)),
                ('slot_key', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('skipped', 'Skipped')], default='pending', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('completed_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activities.activity')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_tasks', to='enterprises.enterprise')),
            ],
            options={
                'ordering': ['target_date'],
                'indexes': [models.Index(fields=['enterprise', 'status', 'target_date'], name='enterprises_enterpr_c717aa_idx'), models.Index(fields=['assigned_to', 'status'], name='enterprises_assigne_d8b473_idx')],
                'constraints': [models.UniqueConstraint(fields=('enterprise', 'slot_key'), name='uniq_seasontask_slot')],
            },
        ),
    ]
